import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import NavMenu from "./components/navigation/navMenu";

import { MAIN_NAV_ITEMS } from "./constants/navigation";
import { I18nProvider } from "./providers/i18nProvider";
import SideMenu from "./components/navigation/sideMenu";

const geistMono = Geist_Mono({  
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <I18nProvider>
          <SideMenu />
          <NavMenu 
            items={MAIN_NAV_ITEMS} 
            parentClassName="flex fixed top-0 left-[160px] mt-10 gap-6 items-center justify-content z-1" 
            stantdrChildtClassName="mr-4 text-white opacity-50 hover:opacity-100"
            activeChildClassName="text-white-600 font-bold transition-all duration-300 [text-shadow:0_0_5px_rgba(255,255,255,0.8)]"
            translationNamespace="mainNavMenu"
          />
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}

